
  name: cybersf
  version: '3.2.9' # just for humans, typically '1.2+git' or '1.3.2'
  summary: cybersf Hacking Tools Pack – A Penetration Testing Framework # 79 char long summary
  description: Cyber Security Framework & Hacking Tools Pack

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  